### PR TITLE
Feat: Added Product listing page

### PR DESCRIPTION
**Pull request by Richa-rani02**
1. added products in product listing page
2.filter section
3. linked product page to home page
productlistingpagedemo

### CODE REVIEW

**Review by ashishnnnnn — COMMENTED** [review]
Code looks good.. :+1:

**Review by prathmeshjagtap — COMMENTED** [review]
Code looks good and clean,  Just a question why have you applied pointer cursor on the body and not on card's

**Comment by Richa-rani02** [comment]
Cursor pointer is on products-grid, code is minimized that why looking like this
image

**Review by prathmeshjagtap — APPROVED** [review]

**Review by ashishnnnnn — APPROVED** [review]
Approved to merge :+1:

**Pull request merged**
